/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gh.workflow.Sanjay.Alex;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println("Alex was here.");
    }
}
